[build] 
  publish = "dist"
  command = "npm run build"

[dev] 
  publish = "./dist"
  command = "npm run serve"
  targetPort = 8081

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/.netlify/functions/cart-view"
  status = 200


[context.production]
  environment = { SHOPIFY_API_ENDPOINT = "https://the-girls-bathroom-dev.myshopify.com/api/unstable/graphql.json", SHOPIFY_STOREFRONT_API_TOKEN = "a529c836e0cd8f73a1e9d9d39938ae64" }

[context.dev]
  environment = { SHOPIFY_API_ENDPOINT = "https://the-girls-bathroom-dev.myshopify.com/api/unstable/graphql.json", SHOPIFY_STOREFRONT_API_TOKEN = "a529c836e0cd8f73a1e9d9d39938ae64" }
